# Generated by Django 4.0 on 2024-01-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='weeklyassignment',
            name='discussionTopic',
            field=models.ManyToManyField(to='core.DiscussionTopic'),
        ),
        migrations.AlterField(
            model_name='weeklyassignment',
            name='skillVideo',
            field=models.ManyToManyField(to='core.SkillVideo'),
        ),
    ]
